"""core tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 17:12:58.033421
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY = ("audit_events", "signal_events")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)

    op.create_table('progression_states',
    sa.Column('scope_key', sa.String(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('base_lot', sa.String(), nullable=False),
    sa.Column('theoretical_lot', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('mode5_block_trade_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('scope_key', name=op.f('pk_progression_states'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw_message', sa.String(), nullable=False),
    sa.Column('edited_message', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('symbol_raw', sa.String(), nullable=True),
    sa.Column('symbol_mt5', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('entry', sa.String(), nullable=True),
    sa.Column('stop_loss', sa.String(), nullable=True),
    sa.Column('take_profits', sa.JSON(), nullable=True),
    sa.Column('selected_take_profit', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('signal_id', name=op.f('uq_signals_signal_id')),
    sa.UniqueConstraint('source_id', 'source_message_id', name=op.f('uq_signals_source_id'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_state'), ['state'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_pk', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_pk'], ['signals.id'], name=op.f('fk_signal_events_signal_pk_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_events'))
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_signal_pk'), ['signal_pk'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_pk', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('signal_fingerprint', sa.String(), nullable=False),
    sa.Column('progression_scope_key', sa.String(), nullable=False),
    sa.Column('telegram_source_id', sa.String(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('telegram_timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw_signal', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('symbol_raw', sa.String(), nullable=False),
    sa.Column('symbol_mt5', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('requested_entry', sa.String(), nullable=True),
    sa.Column('actual_entry', sa.String(), nullable=True),
    sa.Column('stop_loss', sa.String(), nullable=False),
    sa.Column('tp1', sa.String(), nullable=True),
    sa.Column('tp2', sa.String(), nullable=True),
    sa.Column('tp3', sa.String(), nullable=True),
    sa.Column('selected_tp', sa.String(), nullable=False),
    sa.Column('risk_mode', sa.Integer(), nullable=False),
    sa.Column('base_lot', sa.String(), nullable=False),
    sa.Column('theoretical_lot', sa.String(), nullable=False),
    sa.Column('executed_lot', sa.String(), nullable=False),
    sa.Column('volume_min', sa.String(), nullable=False),
    sa.Column('volume_max', sa.String(), nullable=False),
    sa.Column('volume_step', sa.String(), nullable=False),
    sa.Column('volume_capped_at_max', sa.Boolean(), nullable=False),
    sa.Column('estimated_risk', sa.String(), nullable=False),
    sa.Column('estimated_reward', sa.String(), nullable=False),
    sa.Column('estimated_rr', sa.String(), nullable=True),
    sa.Column('equity_risk_percent', sa.String(), nullable=True),
    sa.Column('balance_before', sa.String(), nullable=False),
    sa.Column('equity_before', sa.String(), nullable=False),
    sa.Column('margin_before', sa.String(), nullable=False),
    sa.Column('free_margin_before', sa.String(), nullable=False),
    sa.Column('equity_lock_enabled', sa.Boolean(), nullable=False),
    sa.Column('equity_lock_value', sa.String(), nullable=True),
    sa.Column('mt5_order_id', sa.Integer(), nullable=True),
    sa.Column('mt5_deal_id', sa.Integer(), nullable=True),
    sa.Column('mt5_position_id', sa.Integer(), nullable=True),
    sa.Column('execution_retcode', sa.Integer(), nullable=True),
    sa.Column('execution_message', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.String(), nullable=True),
    sa.Column('realized_profit', sa.String(), nullable=True),
    sa.Column('realized_swap', sa.String(), nullable=True),
    sa.Column('realized_commission', sa.String(), nullable=True),
    sa.Column('net_profit', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('realized_r_multiple', sa.String(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('balance_after', sa.String(), nullable=True),
    sa.Column('equity_after', sa.String(), nullable=True),
    sa.Column('telegram_received_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_requested_at', sa.DateTime(), nullable=True),
    sa.Column('broker_response_at', sa.DateTime(), nullable=True),
    sa.Column('position_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_pk'], ['signals.id'], name=op.f('fk_trades_signal_pk_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('mt5_position_id', name=op.f('uq_trades_mt5_position_id')),
    sa.UniqueConstraint('signal_fingerprint', name=op.f('uq_trades_signal_fingerprint'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_progression_scope_key'), ['progression_scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_signal_pk'), ['signal_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol_mt5'), ['symbol_mt5'], unique=False)

    # ### end Alembic commands ###
    # §43 immutable-style audit + §7 persisted transitions: the DB refuses edits/deletes.
    for table in APPEND_ONLY:
        for action in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER {table}_no_{action.lower()} BEFORE {action} ON {table} "
                f"BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END"
            )


def downgrade() -> None:
    for table in APPEND_ONLY:
        for action in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_no_{action}")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol_mt5'))
        batch_op.drop_index(batch_op.f('ix_trades_signal_pk'))
        batch_op.drop_index(batch_op.f('ix_trades_progression_scope_key'))

    op.drop_table('trades')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_signal_pk'))

    op.drop_table('signal_events')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_state'))
        batch_op.drop_index(batch_op.f('ix_signals_source_id'))
        batch_op.drop_index(batch_op.f('ix_signals_fingerprint'))

    op.drop_table('signals')
    op.drop_table('settings')
    op.drop_table('progression_states')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
